// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-yDedP7I3NNfJZn_wixqKidyAp-pTKgU',
    appId: '1:52578127795:web:62014e1f7911035b8645c6',
    messagingSenderId: '52578127795',
    projectId: 'quickmedical-app',
    authDomain: 'quickmedical-app.firebaseapp.com',
    storageBucket: 'quickmedical-app.appspot.com',
    measurementId: 'G-9ZWH46LWHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyo4DOcQMZHYT_hsTKgLo2eheDcYdEFuU',
    appId: '1:52578127795:android:02266b2fd6ddcd7b8645c6',
    messagingSenderId: '52578127795',
    projectId: 'quickmedical-app',
    storageBucket: 'quickmedical-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDztC67GQEbgoAY7h_v-0stzo6CvGVojdE',
    appId: '1:52578127795:ios:eecc5dd9c0525d188645c6',
    messagingSenderId: '52578127795',
    projectId: 'quickmedical-app',
    storageBucket: 'quickmedical-app.appspot.com',
    iosBundleId: 'com.example.medicalstoreapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDztC67GQEbgoAY7h_v-0stzo6CvGVojdE',
    appId: '1:52578127795:ios:eecc5dd9c0525d188645c6',
    messagingSenderId: '52578127795',
    projectId: 'quickmedical-app',
    storageBucket: 'quickmedical-app.appspot.com',
    iosBundleId: 'com.example.medicalstoreapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-yDedP7I3NNfJZn_wixqKidyAp-pTKgU',
    appId: '1:52578127795:web:53f3bc06a7dfb1de8645c6',
    messagingSenderId: '52578127795',
    projectId: 'quickmedical-app',
    authDomain: 'quickmedical-app.firebaseapp.com',
    storageBucket: 'quickmedical-app.appspot.com',
    measurementId: 'G-4V2WB4LKK0',
  );

}